name: Dev-Deploy-All
on:  
  workflow_dispatch:
jobs:
  delta:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3dev-delta
    secrets:
      inherit
  epsilon:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3dev-epsilon
    secrets:
      inherit      
  zeta:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3dev-zeta
    secrets:
      inherit
  ahld:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3us-ahld
    secrets:
      inherit
  albt:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3us-albt
    secrets:
      inherit
  brcp:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3us-brcp
    secrets:
      inherit
  gmi:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3us-gmi
    secrets:
      inherit
  harr:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3us-harr
    secrets:
      inherit
  krog:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3us-krog
    secrets:
      inherit
  prc:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3us-prc
    secrets:
      inherit
  srai:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3us-srai
    secrets:
      inherit
  stgalbt:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3us-stgalbt
    secrets:
      inherit
  stgsams:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3us-stgsams
    secrets:
      inherit
  walm:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3us-walm
    secrets:
      inherit
  weis:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3us-weis
    secrets:
      inherit
  wmdp:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3us-wmdp
    secrets:
      inherit
