name: Dev-Destroy-All
on:  
  workflow_dispatch:
jobs:
  delta:
    name: Destroy development
    uses: ./.github/workflows/destroy.yml
    with:
      environment: Development
      working-folder: r3dev-delta
    secrets:
      inherit