name: Dev-Deploy-All
on:  
  workflow_dispatch:
jobs:
  delta:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3dev-delta
    secrets:
      inherit
  epsilon:
    name: Deploy development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3dev-epsilon
    secrets:
      inherit      